language: java
dist: bionic
install: true
script:
 - cp config/config-travis.json config/config.json
 - scripts/run.py -b -m -e
before_install:
 - sudo apt-get update
 - sudo apt-get install -y r-base
notifications:
  email: false
  on_success: change
  on_failure: always
