---
title: "TTC Social Media case benchmark report"
output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: no
  pdf_document:
    highlight: zenburn
    number_sections: yes
    toc: no
    keep_tex: true
params:
classoption: a4paper
---

```{r setup, include=FALSE}
library(tidyverse)
library(plyr)
library(RColorBrewer)

gm_mean = function(x, na.rm=TRUE) {
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}

nice_y_axis = function() {
  options(scipen=999)
  
  # y axis labels
  longticks = c(F, T, F, F, F, F, F, F, T)
  shortticks = 2:10
  range = -6:6
  
  ooms = 10^range
  
  ybreaks = as.vector(shortticks %o% ooms)
  ylabels = as.character(ybreaks * longticks)
  ylabels = gsub("^0$", "", ylabels)
  
  list(ybreaks = ybreaks, ylabels = ylabels)
}
```


```{r loading and cleaning, echo=FALSE}
df = read_delim("../output/output.csv", delim = ";")
df = df[df$MetricName == "Time", ]
df = df[df$PhaseName != "Initialization", ]
df$MetricValue = as.numeric(df$MetricValue)
# convert from nanoseconds to seconds
df$MetricValue = df$MetricValue / 10^9

# drop most tools for now
#df = df[df$Tool == "EMFSolutionViatra" | df$Tool == "SQLSolution", ]

### Captions

### Neo4j
df$Tool = gsub("^Neo4jSolutionBatch$", "Neo4j Batch", df$Tool)
df$Tool = gsub("^Neo4jSolution$", "Neo4j Incremental", df$Tool)
df = df[!startsWith(df$Tool, "Neo4jSolution"), ]

#df$Tool = gsub("Neo4jSolution_explicit_component_periodic", "Neo4j Incremental", df$Tool)
#df$Tool = gsub("Neo4jSolution_explicit_component_algo", "Neo4j Incremental 2)", df$Tool)

## Differential
df$Tool = gsub("^differential$", "Differential Dataflow (1 thread)", df$Tool)
df$Tool = gsub("^differential-08$", "Differential Dataflow (8 threads)", df$Tool)

## Naiad
# Drop middle of the road Naiad results
df = df[df$Tool != "Naiad-2-Thread" & df$Tool != "Naiad-4-Thread" & df$Tool != "Naiad-6-Thread", ]
# df = df[df$Tool != "Naiad-1-Thread" & df$Tool != "Naiad-2-Thread" & df$Tool != "Naiad-4-Thread" & df$Tool != "Naiad-6-Thread", ]
df$Tool = gsub("^Naiad-1-Thread$", "Naiad (1 thread)", df$Tool)
df$Tool = gsub("^Naiad-8-Thread$", "Naiad (8 threads)", df$Tool)

## Drop NMF Parallel solution (buggy) and NMF Transactions solutions
df = df[df$Tool != "NMF-Parallel" & df$Tool != "NMF-Transactions", ]
df$Tool = gsub("^NMF$", "NMF Batch", df$Tool)
df$Tool = gsub("^NMF-Incremental$", "NMF Incremental", df$Tool)

## EMF
df$Tool = gsub("^EMFSolutionXtend$", "Xtend (EMF)", df$Tool)

## SQL
df$Tool = gsub("^SQLSolutionBatch$", "PostgreSQL Batch", df$Tool)
df$Tool = gsub("^SQLSolution$", "PostgreSQL Incremental", df$Tool)

## GraphBLAS
df$Tool = gsub("^GBq1-Batch$", "GraphBLAS Batch", df$Tool)
df$Tool = gsub("^GBq2-Batch$", "GraphBLAS Batch", df$Tool)
df$Tool = gsub("^GBq1-Incr$", "GraphBLAS Incremental", df$Tool)
df$Tool = gsub("^GBq2-Incr-Comment$", "GraphBLAS Incremental", df$Tool)


df$View = factor(df$View, levels=c("Q1", "Q2"))
df$PhaseName = factor(df$PhaseName, levels=c("Load", "Initial", "Update"))
```

## Summary plot

```{r summary plot, echo=FALSE}
df.aggregated = ddply(
  .data = df,
  .variables = c("Tool", "View", "ChangeSet", "PhaseName", "MetricName"),
  #.fun = colwise(mean),
  .fun = colwise(gm_mean)
)

my_brewer = brewer.pal(n = 12, "Paired")[c(1, 2, 3, 4, 5, 6, 9, 10, 7)]
my_brewer

xbreaks = unique(df.aggregated$ChangeSet)
xlabels = paste(xbreaks, sep = "")
yaxis = nice_y_axis()
ggplot(df.aggregated, aes(x=ChangeSet, y=MetricValue, fill=Tool)) +
    geom_point(alpha=1.0, aes(col=Tool, shape=Tool, fill=Tool)) +
    geom_line(aes(col=Tool, group=Tool)) +
    scale_x_log10(breaks=xbreaks) +  
    scale_y_log10(breaks=c(0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000), labels=c(0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
    annotation_logticks(sides = "l") +
    scale_shape_manual(values = c(0, 15,
                                  1, 21,
                                  2, 17,
                                  5, 23,
                                  6)) +
    scale_color_manual(values=my_brewer) +
    scale_fill_manual(values=my_brewer) +
    #facet_grid(View~PhaseName, drop=FALSE) +
    facet_grid(PhaseName~View, drop=FALSE, scale = "free_y") +
    xlab("Model size") +
    ylab("Execution time [s]") +
    theme_bw() +
    theme(legend.position="bottom")

#ggsave(file="results.pdf", width=250, height=170, units="mm")
ggsave(file="results.pdf", width=210, height=300, units="mm")
```

## Plot of update iterations

```{r update plot}
df = df[df$PhaseName == "Update", ]
df.aggregated = ddply(
  .data = df,
  .variables = c("Tool", "View", "ChangeSet", "PhaseName", "Iteration", "MetricName"),
  #.fun = colwise(mean),
  .fun = colwise(gm_mean)
)

xbreaks = unique(df.aggregated$ChangeSet)
xlabels = paste(xbreaks, sep = "")
yaxis = nice_y_axis()
ggplot(df.aggregated, aes(x=Iteration, y=MetricValue, fill=Tool)) +
    geom_point(aes(col=Tool, shape=Tool)) +
    geom_line(aes(col=Tool, group=Tool)) +
    scale_x_log10(breaks=xbreaks) +  
    scale_y_log10(breaks=yaxis$ybreaks, labels=yaxis$ylabels) +
    scale_shape_manual(values = seq(0,24)) +
    facet_grid(ChangeSet~View, drop=FALSE) +
    xlab("Model size") +
    ylab("Execution time [s]") +
    theme_bw()
ggsave(file="results-neo4j-iterations.pdf", width=250, height=750, units="mm")
```
